# **Welcome to the Notebook**

### Task 1 - Set up the project

Installing the needed modules.

In [ ]:
!pip python-dotenv pyspark
%pip install -U openai

ERROR: unknown command "python-dotenv"
Requirement already satisfied: openai in /usr/local/lib/python3.13/dist-packages (3.14.1)
Requirement already satisfied: anyio<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from openai) (4.14.2)
Requirement already satisfied: httpx2<3,>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from openai) (2.12.0)
Requirement already satisfied: jiter<1,>=0.16.0 in /usr/local/lib/python3.13/dist-packages (from openai) (0.16.0)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13 in /usr/local/lib/python3.13/dist-packages (from openai) (2.13.5)
Requirement already satisfied: sniffio in /usr/local/lib/python3.13/dist-packages (from openai) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.13/dist-packages (from openai) (4.16.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=4.10.0->openai) (3.19)
Requirement already satisfied: httpcore2==2.12.0 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2.7.0->openai) (2.12.0)
Requirement already satisfied: truststore>=0.10 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2.7.0->openai) (0.10.4)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore2==2.12.0->httpx2<3,>=2.7.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.10.13->openai) (0.4.4)

Imporint the modules

In [ ]:
from dotenv import load_dotenv
import os
from openai import OpenAI
import pandas as pd
import numpy as np

from pyspark.sql import SparkSession
from pyspark.sql.functions import concat_ws
from pyspark.sql import functions as F
from pyspark.sql.types import ArrayType, FloatType

from pyspark.ml.feature import VectorAssembler, PCA
from pyspark.ml.clustering import KMeans
import plotly.express as px

Setup the OpenAI API

In [ ]:
load_dotenv(dotenv_path= 'apikey.env.txt')
APIKEY = os.getenv('APIKEY')
print(f"API Key loaded: {APIKEY}") # Added for debugging
client = OpenAI(api_key=APIKEY)

Create a Spark session

In [ ]:
spark = SparkSession.builder.appName("ProductRecommenderSystem").getOrCreate()

Loading the dataset

In [ ]:
file_path ='products_dataset.csv'
df = spark.read.csv(file_path, header=True, inferSchema=True,samplingRatio=1)
df.show()

+----------+--------------------+--------------------+
|product_id|               title|         description|
+----------+--------------------+--------------------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|
|        P1|Turmode 30 ft. RP...|If you need more ...|
|        P2|Large Tapestry Bo...|Polyester cover r...|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|
|        P4|Men's Crazy Horse...|This 9 in. black ...|
|        P5|Mariana 6 ft. Mul...|With robust struc...|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|
|        P9|Traditional Silve...|This transitional...|
|       P10|15 in. x 59 in. O...|Its easy to add a...|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|
+----------+--------------------+--------------------+
only showing top 20 rows

List of 8 products recently viewed by the user.

In [ ]:
recently_viewed_products = [
    'P316',
    'P333',
    'P1115',
    'P1691',
    'P1082',
    'P397',
    'P1441',
    'P1054',
]

### Task 2 - Prepare the dataset

Combine `title` and `description` Columns

In [ ]:
df = df.withColumn("combined_text", concat_ws(" ", "title", "description"))
df.show()

+----------+--------------------+--------------------+--------------------+
|product_id|               title|         description|       combined_text|
+----------+--------------------+--------------------+--------------------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|Men's 3X Large Ca...|
|        P1|Turmode 30 ft. RP...|If you need more ...|Turmode 30 ft. RP...|
|        P2|Large Tapestry Bo...|Polyester cover r...|Large Tapestry Bo...|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|16-Gauge-Sinks Ve...|
|        P4|Men's Crazy Horse...|This 9 in. black ...|Men's Crazy Horse...|
|        P5|Mariana 6 ft. Mul...|With robust struc...|Mariana 6 ft. Mul...|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|5 gal. #650C-2 Po...|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|7/8 in. x 4-1/2 i...|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|Ring Gold Bar Car...|
|        P9|Traditional Silve...|This transitional...|Traditional Silve...|
|       P10|15 in. x 59 in. O...|Its easy to add a...|15 in. x 59 in. O...|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|1 qt. #350F-7 Wil...|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|Anthracite Cordle...|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|SlimGrip 78-Inch ...|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|6 in. x 28 in. x ...|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|Espresso Cordless...|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|5 gal. #BL-W10 Ma...|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|Eleyn 26 in. Indo...|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|1 qt. #M400-5 Bab...|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|10 in. x 4 in. x ...|
+----------+--------------------+--------------------+--------------------+
only showing top 20 rows

get the combined_text column and convert it into a list

In [ ]:
list_combined_text = df.select("combined_text").rdd.flatMap(lambda x: x).collect()
print(list_combined_text[:4])

["Men's 3X Large Carbon Heather Cotton/Polyester Rain Defender Paxton Heavyweight Hooded Zip-Front Sweatshirt This heavyweight, water-repellent hooded sweatshirt has a zip front for fast layering. ORIGINAL FIT. 13 oz., 75% cotton/25% polyester blend with Rain Defender durable water repellent. Attached, jersey-lined three-piece hood with drawcord closure. Antique-finish brass front zipper. Two front hand-warmer pockets have a hidden security pocket inside. Stretchable, spandex-reinforced rib-knit cuffs and waistband. Locker loop facilitates hanging.", "Turmode 30 ft. RP TNC Female to RP TNC Male Adapter Cable If you need more length between your existing wireless device and Hi-Gain Antenna, this is the product for you. It's compatible with most Wi-Fi Antennas, so it is easy for you to extend your wireless network. Just replace your existing cable that runs between your wireless device and Antenna and you're ready to use your network with extended range.", 'Large Tapestry Bolster Bed Polyester cover resembling rich Italian tapestries wraps your pet in comfort and style. 100% recycled polyester high loft MemoryFiber fill keeps pets elevated off cold floors for relief on tired joints and pressure points. A great fit for pets up to 100 lbs. Zippered removable cover is machine washable in cold water only. To dry, use a delicate cycle or gentle setting with very low heat.', '16-Gauge-Sinks Vessel Sink in White with Faucet It features a rectangle shape. This vessel set is designed to be installed as a undermount vessel set. It is constructed with ceramic. This vessel set comes with an enamel glaze finish in White color. It is designed for a deck mount faucet.']

Use OpenAI text embedding model to create the vector embeddings.

In [ ]:
response = client.embeddings.create(
    input=list_combined_text,
    model="text-embedding-3-small",
    dimensions= 512
)
embedding_vectors = [d.embedding for d in response.data]
embedding_vectors[:2]

[[0.04266357421875,
  0.0208740234375,
  -0.01364898681640625,
  -0.002056121826171875,
  0.0031986236572265625,
  -0.037261962890625,
  0.0272216796875,
  0.07830810546875,
  0.05499267578125,
  -0.06280517578125,
  0.04425048828125,
  0.048248291015625,
  -0.06781005859375,
  0.02520751953125,
  0.0225677490234375,
  0.06396484375,
  0.10101318359375,
  -0.0307769775390625,
  -0.0889892578125,
  0.07061767578125,
  -0.058013916015625,
  0.06719970703125,
  -0.034759521484375,
  -0.07373046875,
  0.034454345703125,
  0.043243408203125,
  -0.052520751953125,
  0.0249786376953125,
  0.051055908203125,
  -0.0172119140625,
  -0.0031528472900390625,
  -0.0221099853515625,
  0.01910400390625,
  -0.0245513916015625,
  0.044921875,
  -0.066650390625,
  -0.02105712890625,
  0.10443115234375,
  -0.038665771484375,
  0.025634765625,
  0.02349853515625,
  -0.052764892578125,
  0.0181732177734375,
  -0.06268310546875,
  0.032623291015625,
  0.03680419921875,
  0.0259552001953125,
  0.0240631103515625,
  -0.033538818359375,
  0.0179443359375,
  -0.03167724609375,
  -0.0231475830078125,
  -0.0556640625,
  0.05255126953125,
  -0.036346435546875,
  -0.025543212890625,
  -0.0479736328125,
  -0.04473876953125,
  0.0165252685546875,
  -0.0233917236328125,
  -0.02117919921875,
  -0.021484375,
  -0.031890869140625,
  -0.006137847900390625,
  -0.0275115966796875,
  -0.033416748046875,
  0.0109405517578125,
  -0.017303466796875,
  0.00803375244140625,
  -0.0418701171875,
  0.061798095703125,
  0.041351318359375,
  0.0311126708984375,
  -0.0294342041015625,
  -0.08154296875,
  -0.0030956268310546875,
  0.00394439697265625,
  -0.08282470703125,
  0.01184844970703125,
  0.035675048828125,
  -0.0171966552734375,
  0.07110595703125,
  -0.024261474609375,
  -0.0180206298828125,
  -0.057098388671875,
  0.003143310546875,
  -0.019683837890625,
  0.01270294189453125,
  -0.0057830810546875,
  -0.01221466064453125,
  0.02923583984375,
  0.005054473876953125,
  0.0196533203125,
  -0.029571533203125,
  -0.0435791015625,
  0.0018110275268554688,
  -0.0196075439453125,
  -0.03717041015625,
  -0.031341552734375,
  0.01187896728515625,
  -0.028076171875,
  -0.0179595947265625,
  -0.0101165771484375,
  0.01215362548828125,
  -0.057098388671875,
  -0.00887298583984375,
  -0.10595703125,
  -0.0059051513671875,
  0.01033782958984375,
  -0.0208892822265625,
  -0.09954833984375,
  0.0703125,
  0.032562255859375,
  0.0706787109375,
  -0.03692626953125,
  -0.0355224609375,
  0.031707763671875,
  0.00324249267578125,
  -0.004573822021484375,
  0.0654296875,
  0.0213165283203125,
  0.0621337890625,
  -0.0124359130859375,
  -0.018218994140625,
  0.0005235671997070312,
  -0.006801605224609375,
  -0.04046630859375,
  -0.052642822265625,
  0.005035400390625,
  -0.0008225440979003906,
  0.03717041015625,
  0.02484130859375,
  0.07598876953125,
  -0.0229034423828125,
  -0.017242431640625,
  0.0166015625,
  0.05242919921875,
  0.00951385498046875,
  -0.032012939453125,
  -0.12017822265625,
  -0.0305023193359375,
  -0.047515869140625,
  -0.0229034423828125,
  -0.004009246826171875,
  0.024139404296875,
  0.0204620361328125,
  -0.013916015625,
  -0.006099700927734375,
  -0.050048828125,
  0.083740234375,
  -0.05548095703125,
  -0.06353759765625,
  0.078369140625,
  0.028350830078125,
  -0.0986328125,
  -0.0113677978515625,
  0.06463623046875,
  0.043121337890625,
  -0.055145263671875,
  -0.033294677734375,
  -0.06622314453125,
  0.003902435302734375,
  -0.00821685791015625,
  -0.00045680999755859375,
  0.127197265625,
  0.00011664628982543945,
  0.06988525390625,
  -0.08416748046875,
  -0.08538818359375,
  -0.03564453125,
  0.0023708343505859375,
  -0.044586181640625,
  0.0027790069580078125,
  0.0230560302734375,
  0.021728515625,
  0.03662109375,
  -0.08258056640625,
  0.0198974609375,
  -0.031982421875,
  -0.1253662109375,
  -0.0090484619140625,
  -0.04522705078125,
  0.06353759765625,
  -0.0506591796875,
  -0.04412841796875,
  -0.0435791015625,
  0.031768798828125,
  0.0164031982421875,
  0.0171661376953125,
  0.01099395751953125,
  0.0018396377563476562,
  0.028350830078125,
  -0.0254974365234375,
  -0.0035114288330078125,
  -0.034149169921875,
  -0.0859375,
  0.0231781005859375,
  0.0711669921875,
  0.005641937255859375,
  0.0859375,
  -0.050628662109375,
  0.07867431640625,
  0.0303497314453125,
  0.01910400390625,
  -0.048736572265625,
  0.00870513916015625,
  -0.0098419189453125,
  -0.0079193115234375,
  -0.06512451171875,
  -0.0293731689453125,
  0.0545654296875,
  0.00400543212890625,
  -0.041046142578125,
  -0.003765106201171875,
  -0.0089569091796875,
  -0.0022258758544921875,
  0.015716552734375,
  -0.01244354248046875,
  0.0207061767578125,
  0.0528564453125,
  -0.07025146484375,
  0.03173828125,
  -0.062408447265625,
  0.0145111083984375,
  -0.05145263671875,
  0.06072998046875,
  0.057952880859375,
  0.04534912109375,
  0.0143890380859375,
  -0.06298828125,
  0.031280517578125,
  0.024383544921875,
  -0.07818603515625,
  0.01140594482421875,
  -0.06378173828125,
  0.057708740234375,
  0.0011005401611328125,
  -0.04052734375,
  -0.0335693359375,
  -0.01392364501953125,
  -0.06927490234375,
  -0.002162933349609375,
  0.0207672119140625,
  0.06280517578125,
  0.017181396484375,
  0.01224517822265625,
  -0.02630615234375,
  -0.042572021484375,
  0.05377197265625,
  -0.02606201171875,
  0.034942626953125,
  -0.0303192138671875,
  -0.04510498046875,
  0.04498291015625,
  0.0295562744140625,
  0.049591064453125,
  0.0128326416015625,
  -0.0008034706115722656,
  -0.023223876953125,
  -0.03167724609375,
  -0.06683349609375,
  0.0035572052001953125,
  -0.0128173828125,
  0.0034332275390625,
  -0.0181121826171875,
  0.051666259765625,
  0.0404052734375,
  -0.058258056640625,
  0.024200439453125,
  0.0440673828125,
  -0.00989532470703125,
  0.061798095703125,
  0.0352783203125,
  0.09423828125,
  -0.044921875,
  0.0499267578125,
  -0.002811431884765625,
  0.0557861328125,
  0.0208740234375,
  0.06988525390625,
  -0.06884765625,
  -0.036773681640625,
  0.007419586181640625,
  0.01529693603515625,
  0.0157623291015625,
  0.046722412109375,
  0.039093017578125,
  0.0645751953125,
  0.00273895263671875,
  0.001819610595703125,
  0.0178375244140625,
  -0.0235595703125,
  -0.0188751220703125,
  -0.0172119140625,
  -0.04840087890625,
  -0.0286865234375,
  -0.095947265625,
  0.037109375,
  -0.016204833984375,
  -0.0648193359375,
  0.01898193359375,
  0.07025146484375,
  -0.055450439453125,
  0.0445556640625,
  0.0391845703125,
  0.08905029296875,
  0.044891357421875,
  -0.032806396484375,
  -0.0325927734375,
  -0.011810302734375,
  0.00566864013671875,
  0.037322998046875,
  -0.0535888671875,
  -0.0079193115234375,
  -0.027679443359375,
  -0.04693603515625,
  0.028411865234375,
  0.054595947265625,
  -0.03814697265625,
  -0.04803466796875,
  0.0574951171875,
  0.02960205078125,
  -0.0235137939453125,
  -0.07940673828125,
  0.007198333740234375,
  -0.033905029296875,
  -0.0843505859375,
  -0.042999267578125,
  -0.04010009765625,
  -0.044921875,
  -0.0232391357421875,
  0.00455474853515625,
  -0.002445220947265625,
  -0.0518798828125,
  0.01806640625,
  -0.004058837890625,
  0.025146484375,
  -0.048431396484375,
  0.0241546630859375,
  0.006343841552734375,
  -0.0248870849609375,
  -0.0413818359375,
  -0.027069091796875,
  -0.018707275390625,
  0.050140380859375,
  -0.0548095703125,
  0.0189666748046875,
  0.020599365234375,
  -0.00484466552734375,
  -0.0026092529296875,
  0.016510009765625,
  0.052764892578125,
  -0.02008056640625,
  -0.0139617919921875,
  0.0201416015625,
  -0.0251617431640625,
  0.06072998046875,
  -0.049407958984375,
  0.05792236328125,
  0.00804901123046875,
  0.0237884521484375,
  0.11187744140625,
  -0.0234527587890625,
  -0.0187835693359375,
  0.00270843505859375,
  0.057159423828125,
  -0.0384521484375,
  0.0225830078125,
  -0.0029811859130859375,
  -0.03875732421875,
  0.034881591796875,
  0.0633544921875,
  0.0307769775390625,
  -0.015960693359375,
  -0.04974365234375,
  0.0267486572265625,
  0.014739990234375,
  0.07244873046875,
  -0.023345947265625,
  -0.0284881591796875,
  0.052459716796875,
  0.04986572265625,
  0.028594970703125,
  0.095703125,
  0.08404541015625,
  0.0020122528076171875,
  -0.025482177734375,
  0.006153106689453125,
  0.06219482421875,
  -0.02734375,
  0.04705810546875,
  -0.0731201171875,
  -0.00121307373046875,
  -0.042999267578125,
  -0.0159759521484375,
  -0.0100555419921875,
  0.0433349609375,
  0.0374755859375,
  0.0175628662109375,
  0.074951171875,
  -0.0103302001953125,
  0.051055908203125,
  -0.058258056640625,
  0.04986572265625,
  0.02386474609375,
  -0.00360107421875,
  -0.0194854736328125,
  0.0711669921875,
  -0.054931640625,
  -0.051116943359375,
  -0.032928466796875,
  0.0275726318359375,
  0.00615692138671875,
  0.048187255859375,
  0.022491455078125,
  0.117919921875,
  0.042510986328125,
  -0.0018482208251953125,
  -0.055328369140625,
  0.07373046875,
  -0.05218505859375,
  -0.034454345703125,
  -0.0145416259765625,
  -0.0445556640625,
  -0.01654052734375,
  0.05718994140625,
  0.043548583984375,
  -0.10357666015625,
  -0.0968017578125,
  0.004856109619140625,
  -0.01023101806640625,
  -0.026336669921875,
  0.10296630859375,
  0.0286407470703125,
  -0.08355712890625,
  -0.005245208740234375,
  -0.061065673828125,
  -0.006622314453125,
  -0.007251739501953125,
  0.04400634765625,
  -0.003032684326171875,
  0.05242919921875,
  0.003711700439453125,
  -0.0230712890625,
  0.0010862350463867188,
  -0.006664276123046875,
  0.059783935546875,
  0.01416778564453125,
  -0.064697265625,
  -0.055938720703125,
  0.0153656005859375,
  0.025634765625,
  -0.0745849609375,
  0.0258331298828125,
  -0.0232696533203125,
  0.0679931640625,
  -0.0051116943359375,
  0.0457763671875,
  -0.0009531974792480469,
  -0.004207611083984375,
  0.041656494140625,
  -0.07000732421875,
  0.07000732421875,
  -0.033538818359375,
  -0.07012939453125,
  0.0096588134765625,
  0.032958984375,
  -0.004302978515625,
  0.0994873046875,
  -0.0504150390625,
  -0.01549530029296875,
  -0.05657958984375,
  0.0123138427734375,
  0.0225830078125,
  0.0418701171875,
  0.02520751953125,
  -0.011749267578125,
  -0.00855255126953125,
  -0.05084228515625,
  -0.05670166015625,
  0.005908966064453125,
  -0.01580810546875,
  -0.050384521484375,
  -0.035125732421875,
  -0.007587432861328125,
  0.03411865234375,
  -0.031402587890625,
  0.07598876953125,
  -0.049530029296875,
  -0.041534423828125,
  0.0217742919921875,
  -0.02459716796875,
  -0.00759124755859375,
  -0.0176849365234375,
  0.0023021697998046875,
  -0.037750244140625,
  -0.035888671875,
  -0.03985595703125,
  0.1124267578125,
  -0.024749755859375,
  0.03643798828125,
  0.0302734375,
  0.0191192626953125,
  -0.09051513671875,
  0.03277587890625,
  0.044219970703125,
  0.07269287109375,
  0.0186920166015625,
  0.00665283203125,
  0.025299072265625,
  0.00965118408203125,
  0.040435791015625],
 [0.044097900390625,
  0.00905609130859375,
  0.0269927978515625,
  -0.01401519775390625,
  -0.09368896484375,
  -0.03839111328125,
  0.006153106689453125,
  0.011474609375,
  0.044158935546875,
  0.06884765625,
  -0.010009765625,
  0.04412841796875,
  -0.01119232177734375,
  -0.007289886474609375,
  0.0433349609375,
  -0.0845947265625,
  -0.019927978515625,
  -0.032318115234375,
  -0.07696533203125,
  0.1295166015625,
  0.0042266845703125,
  0.08056640625,
  -0.0222625732421875,
  -0.0267791748046875,
  -0.0194091796875,
  0.048736572265625,
  0.015716552734375,
  0.06756591796875,
  0.03790283203125,
  -0.03662109375,
  -0.031341552734375,
  -0.06304931640625,
  -0.035125732421875,
  -0.037384033203125,
  -0.0257568359375,
  -0.016571044921875,
  -0.00998687744140625,
  -0.00838470458984375,
  0.038909912109375,
  -0.042205810546875,
  0.023193359375,
  0.0210418701171875,
  -0.0217742919921875,
  -0.0005373954772949219,
  0.0116119384765625,
  0.00534820556640625,
  0.0125579833984375,
  0.042144775390625,
  0.03533935546875,
  -0.00826263427734375,
  -0.00010567903518676758,
  0.04791259765625,
  -0.07220458984375,
  0.0439453125,
  -0.08563232421875,
  0.10723876953125,
  -0.021759033203125,
  -0.0235443115234375,
  -0.006084442138671875,
  -0.0234222412109375,
  -0.08026123046875,
  -0.048797607421875,
  0.03167724609375,
  -0.055877685546875,
  0.021820068359375,
  -2.682209014892578e-06,
  -0.01922607421875,
  -0.0089111328125,
  -0.0858154296875,
  0.0027313232421875,
  0.0318603515625,
  -0.045501708984375,
  -0.04022216796875,
  -0.01270294189453125,
  0.005634307861328125,
  -0.020965576171875,
  -0.05841064453125,
  0.0304718017578125,
  0.034576416015625,
  0.0292205810546875,
  -0.02410888671875,
  0.00843048095703125,
  -0.0811767578125,
  0.0078887939453125,
  0.003871917724609375,
  -0.004421234130859375,
  -0.0655517578125,
  -0.06561279296875,
  -0.034210205078125,
  0.031829833984375,
  0.056427001953125,
  -0.05230712890625,
  0.08941650390625,
  -0.04351806640625,
  -0.036224365234375,
  -0.06561279296875,
  -0.047332763671875,
  -0.0184326171875,
  0.04150390625,
  0.044708251953125,
  0.047821044921875,
  0.0177001953125,
  -0.0188751220703125,
  -0.0211639404296875,
  0.0081634521484375,
  -0.046844482421875,
  -0.0182952880859375,
  -0.041290283203125,
  -0.024200439453125,
  0.0662841796875,
  -0.025421142578125,
  -0.036041259765625,
  0.00833892822265625,
  -0.06298828125,
  -0.01262664794921875,
  -0.0191650390625,
  0.08331298828125,
  0.014251708984375,
  0.052459716796875,
  0.00937652587890625,
  -0.05426025390625,
  0.04443359375,
  0.0254058837890625,
  -0.128662109375,
  0.0161590576171875,
  -0.02069091796875,
  -0.059906005859375,
  0.007171630859375,
  0.03582763671875,
  0.0467529296875,
  0.047027587890625,
  0.00841522216796875,
  0.022064208984375,
  -0.0002465248107910156,
  -0.04412841796875,
  0.0029449462890625,
  -0.01271820068359375,
  -0.024810791015625,
  0.0270538330078125,
  -0.025390625,
  0.042388916015625,
  -0.043304443359375,
  0.021484375,
  -0.04595947265625,
  -0.0171051025390625,
  0.038116455078125,
  -0.06707763671875,
  0.0027637481689453125,
  -0.059783935546875,
  -0.006221771240234375,
  -0.1263427734375,
  -0.04376220703125,
  -0.059722900390625,
  -0.0299072265625,
  0.009857177734375,
  -0.046722412109375,
  -0.008209228515625,
  0.0311279296875,
  -0.0224761962890625,
  -0.031768798828125,
  -0.04473876953125,
  -0.00411224365234375,
  -0.09332275390625,
  0.037200927734375,
  -0.01611328125,
  0.006061553955078125,
  0.048492431640625,
  -0.01534271240234375,
  -0.0966796875,
  0.0024471282958984375,
  -0.026214599609375,
  -0.047149658203125,
  -0.07305908203125,
  0.042572021484375,
  0.06280517578125,
  0.0032901763916015625,
  0.00791168212890625,
  -0.06195068359375,
  0.03466796875,
  0.021331787109375,
  -0.04400634765625,
  -0.031982421875,
  0.05523681640625,
  -0.03564453125,
  -0.025543212890625,
  -0.026702880859375,
  0.03375244140625,
  0.065673828125,
  -0.016845703125,
  -0.0233154296875,
  0.041961669921875,
  0.06756591796875,
  -0.03118896484375,
  -0.005023956298828125,
  -0.02557373046875,
  -0.0010862350463867188,
  0.01230621337890625,
  -0.031982421875,
  0.00868988037109375,
  -0.0130767822265625,
  0.06707763671875,
  -0.041015625,
  0.01226043701171875,
  0.024993896484375,
  -0.0914306640625,
  -0.024871826171875,
  -0.014984130859375,
  0.0205078125,
  0.00498199462890625,
  -0.0261688232421875,
  0.07891845703125,
  0.0290069580078125,
  0.00396728515625,
  -0.01151275634765625,
  -0.005825042724609375,
  0.0028667449951171875,
  -0.05718994140625,
  0.016876220703125,
  0.0021610260009765625,
  0.004215240478515625,
  -0.01251983642578125,
  0.0107879638671875,
  0.01146697998046875,
  0.01534271240234375,
  -0.0196380615234375,
  0.0205230712890625,
  -0.0022182464599609375,
  -0.025299072265625,
  0.055328369140625,
  0.0113067626953125,
  -0.002544403076171875,
  0.07318115234375,
  -0.016265869140625,
  -0.063232421875,
  -0.037139892578125,
  0.0236053466796875,
  0.036102294921875,
  -0.030548095703125,
  -0.02667236328125,
  -0.019561767578125,
  -0.003780364990234375,
  0.00014984607696533203,
  0.0694580078125,
  0.09381103515625,
  -0.033905029296875,
  -0.057220458984375,
  -0.02764892578125,
  -0.0272979736328125,
  0.017730712890625,
  -0.056640625,
  0.0218505859375,
  0.053466796875,
  0.08013916015625,
  -0.01849365234375,
  0.0682373046875,
  0.093994140625,
  -0.10137939453125,
  0.0003914833068847656,
  -0.003398895263671875,
  -0.046905517578125,
  0.013214111328125,
  -0.0269012451171875,
  0.0179443359375,
  0.0416259765625,
  0.036865234375,
  0.0013599395751953125,
  0.051116943359375,
  0.006267547607421875,
  0.030487060546875,
  0.01416015625,
  0.06622314453125,
  -0.018646240234375,
  0.0037097930908203125,
  0.015289306640625,
  -0.070068359375,
  0.1124267578125,
  0.08087158203125,
  -0.0087890625,
  0.044403076171875,
  -0.047454833984375,
  -0.03228759765625,
  -0.06610107421875,
  -0.006069183349609375,
  0.0122528076171875,
  -0.041290283203125,
  -0.06195068359375,
  0.0347900390625,
  0.0867919921875,
  0.00980377197265625,
  -0.08489990234375,
  0.037994384765625,
  0.042816162109375,
  -0.05877685546875,
  0.027984619140625,
  0.037017822265625,
  -0.006168365478515625,
  0.003997802734375,
  0.06768798828125,
  0.006496429443359375,
  -0.0762939453125,
  -0.046173095703125,
  0.08514404296875,
  0.0614013671875,
  -0.01490020751953125,
  0.0092926025390625,
  0.01273345947265625,
  0.01934814453125,
  -0.02783203125,
  -0.01412200927734375,
  -0.01983642578125,
  0.03369140625,
  0.0171051025390625,
  -0.01373291015625,
  -0.0380859375,
  0.02679443359375,
  0.0219573974609375,
  -0.007022857666015625,
  -0.0239410400390625,
  -0.01983642578125,
  -0.029510498046875,
  -0.0626220703125,
  -0.03790283203125,
  -0.006710052490234375,
  -0.033935546875,
  -0.0081024169921875,
  -0.049835205078125,
  -0.023834228515625,
  -0.047271728515625,
  -0.039154052734375,
  0.041412353515625,
  -0.0261993408203125,
  0.0087432861328125,
  0.1290283203125,
  -0.06683349609375,
  -0.00678253173828125,
  0.07708740234375,
  -0.035247802734375,
  0.0077362060546875,
  -0.0146636962890625,
  0.0277252197265625,
  0.01329803466796875,
  -0.0163116455078125,
  -0.0469970703125,
  0.07879638671875,
  0.01544189453125,
  0.054962158203125,
  0.083251953125,
  0.01837158203125,
  0.036041259765625,
  0.1251220703125,
  -0.04193115234375,
  0.041748046875,
  0.08056640625,
  0.005283355712890625,
  0.054046630859375,
  0.002777099609375,
  0.09912109375,
  -0.041961669921875,
  0.05084228515625,
  -0.008514404296875,
  -0.03155517578125,
  0.061798095703125,
  -0.027679443359375,
  -0.00673675537109375,
  0.00567626953125,
  0.050506591796875,
  0.00872039794921875,
  0.0703125,
  -0.09552001953125,
  -0.053375244140625,
  -0.031494140625,
  0.093994140625,
  -0.0214996337890625,
  0.05438232421875,
  -0.11102294921875,
  0.058502197265625,
  0.035797119140625,
  0.026611328125,
  0.0193328857421875,
  -0.0140380859375,
  0.051971435546875,
  -0.029510498046875,
  -0.0162200927734375,
  -0.0004096031188964844,
  -0.036041259765625,
  0.0122528076171875,
  -0.033538818359375,
  -0.060760498046875,
  -0.0300445556640625,
  0.00907135009765625,
  0.0227203369140625,
  -0.041961669921875,
  0.0318603515625,
  -0.0271148681640625,
  -0.0430908203125,
  -0.0211334228515625,
  0.051361083984375,
  -0.0030460357666015625,
  0.0222930908203125,
  -0.00467681884765625,
  -0.031707763671875,
  -0.0589599609375,
  -0.1092529296875,
  0.064453125,
  -0.035430908203125,
  -0.0173797607421875,
  0.02313232421875,
  0.1004638671875,
  0.043365478515625,
  -0.0259552001953125,
  -0.0369873046875,
  -0.1207275390625,
  0.0576171875,
  0.09130859375,
  -0.0255889892578125,
  -0.007228851318359375,
  -0.018524169921875,
  0.034942626953125,
  -0.0019664764404296875,
  -0.09197998046875,
  0.0325927734375,
  0.0295867919921875,
  -0.02069091796875,
  -0.0318603515625,
  -0.07513427734375,
  -0.02227783203125,

Let't put the embedding vectors into our original dataframe

Convert embedding vectors list into a Pyspark DataFrame

In [ ]:
features_column_names = [f"embedding_{i}" for i in range(len(embedding_vectors[0]))]
embeddings_df = spark.createDataFrame(embedding_vectors, schema=features_column_names)
embeddings_df.show()

+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+

Add unique `row_id` to each row in the pysaprk dataframe

In [ ]:
embeddings_df = embeddings_df.repartition(1).withColumn("row_id", F.monotonically_increasing_id())
embeddings_df.show()

+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------+

Add unique `row_id` to each row in our main pyspark dataframe `df`

In [ ]:
df = df.repartition(1).withColumn("row_id", F.monotonically_increasing_id())
df.show()

+----------+--------------------+--------------------+--------------------+------+
|product_id|               title|         description|       combined_text|row_id|
+----------+--------------------+--------------------+--------------------+------+
|        P0|Men's 3X Large Ca...|This heavyweight,...|Men's 3X Large Ca...|     0|
|        P1|Turmode 30 ft. RP...|If you need more ...|Turmode 30 ft. RP...|     1|
|        P2|Large Tapestry Bo...|Polyester cover r...|Large Tapestry Bo...|     2|
|        P3|16-Gauge-Sinks Ve...|It features a rec...|16-Gauge-Sinks Ve...|     3|
|        P4|Men's Crazy Horse...|This 9 in. black ...|Men's Crazy Horse...|     4|
|        P5|Mariana 6 ft. Mul...|With robust struc...|Mariana 6 ft. Mul...|     5|
|        P6|5 gal. #650C-2 Po...|BEHR PRO i300 Sem...|5 gal. #650C-2 Po...|     6|
|        P7|7/8 in. x 4-1/2 i...|DEWALT High Perfo...|7/8 in. x 4-1/2 i...|     7|
|        P8|  Ring Gold Bar Cart|This Ring Bar Car...|Ring Gold Bar Car...|     8|
|        P9|Traditional Silve...|This transitional...|Traditional Silve...|     9|
|       P10|15 in. x 59 in. O...|Its easy to add a...|15 in. x 59 in. O...|    10|
|       P11|1 qt. #350F-7 Wil...|BEHR PREMIUM PLUS...|1 qt. #350F-7 Wil...|    11|
|       P12|Anthracite Cordle...|BlindsAvenue ligh...|Anthracite Cordle...|    12|
|       P13|SlimGrip 78-Inch ...|Luverne SlimGrip ...|SlimGrip 78-Inch ...|    13|
|       P14|6 in. x 28 in. x ...|Our Rustic Collec...|6 in. x 28 in. x ...|    14|
|       P15|Espresso Cordless...|"The 2-1/2 in. Co...|Espresso Cordless...|    15|
|       P16|5 gal. #BL-W10 Ma...|BEHR PREMIUM PLUS...|5 gal. #BL-W10 Ma...|    16|
|       P17|Eleyn 26 in. Indo...|This lighted chro...|Eleyn 26 in. Indo...|    17|
|       P18|1 qt. #M400-5 Bab...|BEHR PREMIUM PLUS...|1 qt. #M400-5 Bab...|    18|
|       P19|10 in. x 4 in. x ...|Our faux wood bea...|10 in. x 4 in. x ...|    19|
+----------+--------------------+--------------------+--------------------+------+
only showing top 20 rows

Let's join the two dataframes

In [ ]:
df = df.join(embeddings_df, on="row_id").drop("row_id")
df.show()

+----------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-----------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+-------------------+--------------------+--------------------+--------------------+--------------------+--------------------+

### Task 3 - Cluster products using K-means

Assemble the 512 Embedding Columns into a Single 'features' Column

In [ ]:
assembler = VectorAssembler(inputCols=features_column_names, outputCol="features")
data = assembler.transform(df)
data = data.select(['product_id','title','features'])
data.show()

+----------+--------------------+--------------------+
|product_id|               title|            features|
+----------+--------------------+--------------------+
|        P0|Men's 3X Large Ca...|[0.04266357421875...|
|        P1|Turmode 30 ft. RP...|[0.04409790039062...|
|        P2|Large Tapestry Bo...|[0.0423583984375,...|
|        P3|16-Gauge-Sinks Ve...|[-0.0497436523437...|
|        P4|Men's Crazy Horse...|[0.02626037597656...|
|        P5|Mariana 6 ft. Mul...|[0.060546875,0.04...|
|        P6|5 gal. #650C-2 Po...|[0.00754165649414...|
|        P7|7/8 in. x 4-1/2 i...|[-0.0217437744140...|
|        P8|  Ring Gold Bar Cart|[-4.4417381286621...|
|        P9|Traditional Silve...|[0.03915405273437...|
|       P10|15 in. x 59 in. O...|[6.26564025878906...|
|       P11|1 qt. #350F-7 Wil...|[0.00136566162109...|
|       P12|Anthracite Cordle...|[-0.0231170654296...|
|       P13|SlimGrip 78-Inch ...|[0.02252197265625...|
|       P14|6 in. x 28 in. x ...|[0.01872253417968...|
|       P15|Espresso Cordless...|[-0.0366821289062...|
|       P16|5 gal. #BL-W10 Ma...|[-0.0058975219726...|
|       P17|Eleyn 26 in. Indo...|[-0.0421142578125...|
|       P18|1 qt. #M400-5 Bab...|[0.00733947753906...|
|       P19|10 in. x 4 in. x ...|[-0.0081405639648...|
+----------+--------------------+--------------------+
only showing top 20 rows

Apply K-Means Clustering with 5 Clusters on the `features` Column

In [ ]:
kmeans = KMeans(k=5, featuresCol="features", predictionCol="cluster")
model = kmeans.fit(data)
cluster_data = model.transform(data)
cluster_data.show()

+----------+--------------------+--------------------+-------+
|product_id|               title|            features|cluster|
+----------+--------------------+--------------------+-------+
|        P0|Men's 3X Large Ca...|[0.04266357421875...|      2|
|        P1|Turmode 30 ft. RP...|[0.04409790039062...|      2|
|        P2|Large Tapestry Bo...|[0.0423583984375,...|      4|
|        P3|16-Gauge-Sinks Ve...|[-0.0497436523437...|      3|
|        P4|Men's Crazy Horse...|[0.02626037597656...|      2|
|        P5|Mariana 6 ft. Mul...|[0.060546875,0.04...|      3|
|        P6|5 gal. #650C-2 Po...|[0.00754165649414...|      1|
|        P7|7/8 in. x 4-1/2 i...|[-0.0217437744140...|      2|
|        P8|  Ring Gold Bar Cart|[-4.4417381286621...|      3|
|        P9|Traditional Silve...|[0.03915405273437...|      3|
|       P10|15 in. x 59 in. O...|[6.26564025878906...|      3|
|       P11|1 qt. #350F-7 Wil...|[0.00136566162109...|      1|
|       P12|Anthracite Cordle...|[-0.0231170654296...|      3|
|       P13|SlimGrip 78-Inch ...|[0.02252197265625...|      2|
|       P14|6 in. x 28 in. x ...|[0.01872253417968...|      3|
|       P15|Espresso Cordless...|[-0.0366821289062...|      3|
|       P16|5 gal. #BL-W10 Ma...|[-0.0058975219726...|      1|
|       P17|Eleyn 26 in. Indo...|[-0.0421142578125...|      3|
|       P18|1 qt. #M400-5 Bab...|[0.00733947753906...|      1|
|       P19|10 in. x 4 in. x ...|[-0.0081405639648...|      3|
+----------+--------------------+--------------------+-------+
only showing top 20 rows

### Task 4 - Visualize the clusters

Let's reduce the dimensionality of our features for visualization purpose

`512 dimensions => 2 dimensions`

In [ ]:
pca = PCA(k=2, inputCol="features", outputCol="pca_features")
pca_model = pca.fit(cluster_data )
pca_results = pca_model.transform(cluster_data )
pca_results.show()

+----------+--------------------+--------------------+-------+--------------------+
|product_id|               title|            features|cluster|        pca_features|
+----------+--------------------+--------------------+-------+--------------------+
|        P0|Men's 3X Large Ca...|[0.04266357421875...|      2|[0.18857446687517...|
|        P1|Turmode 30 ft. RP...|[0.04409790039062...|      2|[-0.1739726020281...|
|        P2|Large Tapestry Bo...|[0.0423583984375,...|      4|[-0.0202065381698...|
|        P3|16-Gauge-Sinks Ve...|[-0.0497436523437...|      3|[0.00733770024539...|
|        P4|Men's Crazy Horse...|[0.02626037597656...|      2|[-0.0239812804463...|
|        P5|Mariana 6 ft. Mul...|[0.060546875,0.04...|      3|[-0.0014707727159...|
|        P6|5 gal. #650C-2 Po...|[0.00754165649414...|      1|[0.66985660000214...|
|        P7|7/8 in. x 4-1/2 i...|[-0.0217437744140...|      2|[0.07966090622713...|
|        P8|  Ring Gold Bar Cart|[-4.4417381286621...|      3|[-0.1048041627537...|
|        P9|Traditional Silve...|[0.03915405273437...|      3|[-0.1110996065403...|
|       P10|15 in. x 59 in. O...|[6.26564025878906...|      3|[0.17244675417149...|
|       P11|1 qt. #350F-7 Wil...|[0.00136566162109...|      1|[0.69678537446743...|
|       P12|Anthracite Cordle...|[-0.0231170654296...|      3|[-0.0898811795183...|
|       P13|SlimGrip 78-Inch ...|[0.02252197265625...|      2|[3.04786708159594...|
|       P14|6 in. x 28 in. x ...|[0.01872253417968...|      3|[0.02661442998376...|
|       P15|Espresso Cordless...|[-0.0366821289062...|      3|[0.02568876542779...|
|       P16|5 gal. #BL-W10 Ma...|[-0.0058975219726...|      1|[0.66804203031374...|
|       P17|Eleyn 26 in. Indo...|[-0.0421142578125...|      3|[0.00496604287138...|
|       P18|1 qt. #M400-5 Bab...|[0.00733947753906...|      1|[0.68276556159846...|
|       P19|10 in. x 4 in. x ...|[-0.0081405639648...|      3|[0.11021441818999...|
+----------+--------------------+--------------------+-------+--------------------+
only showing top 20 rows

In [ ]:
pca_df = pca_results.select("product_id", "pca_features","cluster").toPandas()
pca_df.head()
pca_df["x"] = pca_df["pca_features"].apply(lambda x: x[0])
pca_df["y"] = pca_df["pca_features"].apply(lambda x: x[1])

Let's plot the Clusters

In [ ]:
def plot_clusters(pca_df, num_clusters=5):
    """
    Plots a 2D visualization of clusters using Plotly Express.

    Parameters:
    - pca_df (DataFrame): A Pandas DataFrame containing columns 'x', 'y', and 'cluster'.
      'x' and 'y' are the 2D PCA components, and 'cluster' indicates the cluster label.
    - num_clusters (int): The number of unique clusters to display.
    - recently_viewed_df (DataFrame, optional): DataFrame with 'x' and 'y' coordinates for recently viewed products.

    This function creates an interactive scatter plot where each point is colored according to its cluster.
    Recently viewed products are marked as black crosses if provided.

    Returns:
    - fig (Figure): The Plotly figure object for the plot.
    """

    # Create the base cluster plot
    fig = px.scatter(
        pca_df,
        x='x',
        y='y',
        opacity=0.6,
        size_max=4,
        color= pca_df.cluster.astype(str),
        title='2D Visualization of Clusters with Recently Viewed Products',
        labels={'x': 'PCA Component 1', 'y': 'PCA Component 2'},
        category_orders={'cluster': list(range(num_clusters))},
        # show the product id in the tooltip
        hover_data={'product_id': True}

    )

    # Update layout to add legend title and adjust plot settings
    fig.update_layout(legend_title_text='Clusters', legend=dict(x=1, y=1), width=600, height=500)

    return fig

fig = plot_clusters(pca_df)
fig.show()

### Task 5 - Highlight recently viewed products

In [ ]:
print("The user has recently viewed the following products: ", recently_viewed_products)

The user has recently viewed the following products:  ['P316', 'P333', 'P1115', 'P1691', 'P1082', 'P397', 'P1441', 'P1054']

Let's have a look at the records in our `clustered_data` dataframe related to the recently viewed products.

In [ ]:
filtered_data = cluster_data.where(F.col("product_id").isin(recently_viewed_products))
unique_clusters = filtered_data.select("cluster").distinct().rdd.flatMap(lambda x: x).collect()
unique_clusters

[4, 1]

### Task 6 - Recommend products based on recently viewed products

Let's have a look at the recently viewed products titles

In [ ]:
filtered_data.select("title").rdd.flatMap(lambda x: x).collect()

["Mystic Fitz Roy Beige 9' 0 x 12' 0 Area Rug",
 'Florida Shag Beige/Multi 3 ft. x 5 ft. Floral Area Rug',
 '1 gal. #M250-3 Apple Turnover Extra Durable Flat Interior Paint & Primer',
 '1 gal. #HDPG60 Misty Emerald Lake Flat Interior Paint and Primer',
 '1 qt. #S220-7 Molasses Extra Durable Flat Interior Paint & Primer',
 'Modern Gray/Multi 9 ft. x 12 ft. Vibrant Abstract Polyester Area Rug',
 '1 qt. #PPU6-06 Honey Locust Eggshell Enamel Low Odor Interior Paint & Primer',
 'Genet Rust/Red-Brown 8 ft. x 11 ft. Abstract Wool Area Rug']

Let's see the distinct clusters of the recenetly viewed products.

In [ ]:
print(unique_clusters)

[4, 1]

Let's find the possible products for the recommendation.

In [ ]:
possible_recommendations = cluster_data.filter(cluster_data['cluster'].isin(unique_clusters)).filter(~cluster_data['product_id'].isin(recently_viewed_products))

Let's perform a groupby and generate a list of product IDs that can be recommended for each of the clusters.

In [ ]:
recommendations = possible_recommendations.groupby("cluster").agg(
    F.collect_list("product_id").alias("recommendations")
)

recommendations_df = recommendations.toPandas()

recommendations_df["random_recommendations"] = (
    recommendations_df["recommendations"]
    .apply(lambda x: np.random.choice(x, 5, replace=False).tolist())
)

recommendations_df.head()

,cluster,recommendations,random_recommendations
0,4,"[P2, P21, P52, P71, P87, P101, P108, P119, P12...","[P967, P1502, P101, P1001, P1168]"
1,1,"[P6, P11, P16, P18, P24, P26, P30, P33, P40, P...","[P81, P418, P182, P159, P729]"

In [ ]:
# write a python function to display the recommendations
def display_recommendations(row):
  # find the title of the product in df
  product_ids = row['random_recommendations']
  cluster = row.cluster

  titles = data. \
          filter(data["product_id"]. \
          isin(product_ids)).select("title").collect()

  print("\n")
  print("Recommendations for Cluster:", cluster)
  for title in titles:
    print(title[0])

recommendations_df.apply(display_recommendations, axis=1)

Recommendations for Cluster: 4
Pueblo Multi-Colored 3 ft. x 5 ft. Native American Area Rug
Blossom Ivory/Gray 2 ft. x 8 ft. Geometric Aztec Runner Rug
Galena Orange/Brown 9 ft. x 12 ft. Medallion Rectangle Area Rug
Chelsea Red 3 ft. x 14 ft. Border Runner Rug
Drey Ombre Shag Sky Blue 4 ft. x 6 ft. Area Rug


Recommendations for Cluster: 1
1 gal. Home Decorators Collection #HDC-FL14-8 Deer Trail Semi-Gloss Enamel Exterior Paint & Primer
1 qt. #PPU7-03A Sofisticata Hi-Gloss Enamel Interior/Exterior Paint
8 oz. #M530-3 Perennial Blue Satin Enamel Interior/Exterior Paint & Primer Color Sample
1 qt. Black Cherry Water-Based Satin Metallic Interior Paint
1 qt. #T12-20 First Peach Eggshell Enamel Interior Stain -Blocking Paint & Primer

0    None
1    None
dtype: object